/* 
 *  This code was automatically generated by PopJSON (v.1.6.0) for Population (v.0.1.11)
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 *  See the GNU General Public License for more details:
 *  <https://www.gnu.org/licenses/>
 */

#include <math.h>
#include "population.h"

#include <limits.h>
#include <dlfcn.h>
#include <libgen.h>
#include <string.h>
#include <stdio.h>
void *breeding_site;
void (*breeding_site_init)(int *, int *, int *, int *, int *);
void (*breeding_site_destroy)(void);
void (*breeding_site_sim)(int *, int *, double *, double *, double *, char **, char **, double *, double *, int *);

void breeding_site_setup() {
    Dl_info info;
    if (dladdr((void *)breeding_site_setup, &info) == 0) {
        fprintf(stderr, "Could not determine library path\n");
        return;
    }

    char path[PATH_MAX];
    strncpy(path, info.dli_fname, PATH_MAX);
    path[PATH_MAX - 1] = '\0';

    char *dir = dirname(path);
    char fullpath[PATH_MAX];
    snprintf(fullpath, PATH_MAX, "%s/%s", dir, "ex9.dylib");

    breeding_site = dlopen(fullpath, RTLD_NOW);
    if (!breeding_site) { fprintf(stderr, "dlopen failed: %s\n", dlerror()); return; };

    *(void **)(&breeding_site_init) = dlsym(breeding_site, "init");
    if (!breeding_site_init) { fprintf(stderr, "dlsym(init) failed: %s\n", dlerror()); dlclose(breeding_site); return; };

    *(void **)(&breeding_site_sim) = dlsym(breeding_site, "sim");
    if (!breeding_site_sim) { fprintf(stderr, "dlsym(sim) failed: %s\n", dlerror()); dlclose(breeding_site); return; };

    *(void **)(&breeding_site_destroy) = dlsym(breeding_site, "destroy");
    if (!breeding_site_destroy) { fprintf(stderr, "dlsym(destroy) failed: %s\n", dlerror()); dlclose(breeding_site); return; };

    int no, np, ni, ne, st;
    breeding_site_init(&no, &np, &ni, &ne, &st);
}

void breeding_site_finish() {
    breeding_site_destroy();
    dlclose(breeding_site);
}

void breeding_site_sim_wrap(double value[1],
        double y00,
        double pr0,
        double pr1,
        double env0) {
    int tf = 2;
    int rep = 1;
    int success;
    double init[1] = {y00};
    double param[2] = {pr0, pr1};
    double envir[3] = {tf, env0, env0};
    double result[2];
    breeding_site_sim(&tf, &rep, envir, param, init, 0, 0, result, 0, &success);
    value[0] = result[1];
}

#define CHECK(x) (isnan(x) || isinf(x))

#define NumPar 4
#define NumPop 1
#define NumInt 2
#define NumEnv 1

#define d2m 0
#define bs_alpha 1
#define bs_beta 2
#define bs_str 3

#define larva_coef 0
#define larva_mort 1


double dmin(double a, double b) { return a < b ? a : b; }
double dmax(double a, double b) { return a > b ? a : b; }

int TIME;
int TIMEF;

number size_larva;

double *model_param;
double *envir_prec;

double bsvol;
double bsmort;



void fun_hazpar_larva_coef_larva(const number *key, const number num, double *par) {
    double bsitevol_larva[1];
    breeding_site_sim_wrap(bsitevol_larva,key[larva_coef].d,model_param[bs_alpha],model_param[bs_beta],envir_prec[(int)(TIME-1)]);

printf("%d,%g,%g\n",TIME,bsitevol_larva[0],key[larva_coef].d);
    par[0] = bsitevol_larva[0];
}

void fun_hazpar_larva_mort_larva(const number *key, const number num, double *par) {

    double d2m_coef = (((key[larva_coef].d > 0.75)) ? (0.5) : (0.0));

    par[0] = d2m_coef;
}

void prepare_tprobs(int numcol, double *ttprobs, double *tprobs) {
    int rA, rB, i = 0;
    double sum;
    for (i=0, rB=0; rB<numcol; rB++) {
        sum = 1.0;
        for (rA=0; rA<numcol; rA++, i++) {
            tprobs[i] = sum <= 0.0 ? 1.0 : ttprobs[i] / sum;
            sum -= ttprobs[i];
        }
    }
}

void init(int *no, int *np, int *ni, int *ne, int *st) {
    spop2_set_eps(0.01);

    *no = NumPop;
    *np = NumPar;
    *ni = NumInt;
    *ne = NumEnv;
    *st = 0;

    breeding_site_setup();
}

void parnames(char **names, double *param, double *parmin, double *parmax) {
    char temp[NumPop+NumPar+NumInt+NumEnv][256] = {
        "larva",
        "d2m", "bs_alpha", "bs_beta", "bs_str",
        "bsvol", "bsmort",
        "prec",
    };

    int i;
    for (i=0; i<(NumPop+NumPar+NumInt+NumEnv); i++)
        names[i] = strdup(temp[i]);

    param[d2m] = 20;
    parmin[d2m] = 20;
    parmax[d2m] = 20;
    param[bs_alpha] = 1;
    parmin[bs_alpha] = 1;
    parmax[bs_alpha] = 1;
    param[bs_beta] = 0.25;
    parmin[bs_beta] = 0.25;
    parmax[bs_beta] = 0.25;
    param[bs_str] = 200;
    parmin[bs_str] = 200;
    parmax[bs_str] = 200;
}

void destroy(void) {

    if (breeding_site_destroy) { breeding_site_destroy(); }
    if (breeding_site) { dlclose(breeding_site); breeding_site = NULL; }

}

void sim(int *tf, int *rep, double *envir, double *pr, double *y0, char **file_from, char **file_to, double *ret, double *iret, int *success) {

    char *file0 = *file_from;
    char *file1 = *file_to;

    TIME = 0;
    TIMEF = *tf;

    model_param = pr;

    envir_prec = envir + 1; envir += (int)round(*envir) + 1;


    population larva;

    number num = numZERO;
    char arbiters[3];
    number key[3];
    size_larva = numZERO;
    number completed_larva[3];
    double par[2];

    FILE *file;
    number *buff = 0;
    unsigned int buffsz = 0;
    if (file0 && file0[0]!=' ') {
        file = fopen(file0,"rb");
        if (!file) {
            *success = 0;
            goto endall;
        }
        rewind(file);
    }

    if (file0 && file0[0]!=' ') {
        fread(&buffsz, sizeof(unsigned int), 1, file);
        buff = (number *)malloc(buffsz);
        fread(buff, buffsz, 1, file);
        larva = spop2_loadstate(buff);


        free(buff);

    } else {
        arbiters[0] = ACC_MEMORY;
        key[0] = numZERO;
        arbiters[1] = NOAGE_CONST;
        key[1] = numZERO;
        arbiters[2] = STOP;
        key[2] = numZERO;
        larva = spop2_init(arbiters, DETERMINISTIC);
        larva->arbiters[0]->fun_q_par = fun_hazpar_larva_coef_larva;
        larva->arbiters[1]->fun_q_par = fun_hazpar_larva_mort_larva;
        if (y0[0]) { num.d = y0[0]; spop2_add(larva, key, num); }


    }

    if (file0 && file0[0]!=' ') {
        fclose(file);
    }

    bsvol = 0.0;
    bsmort = 0.0;

    size_larva = spop2_size(larva);

    ret[0] = size_larva.d;
    if (CHECK(ret[0])) {goto endall;};

    ret += 1;

    iret[0] = bsvol;
    if (CHECK(iret[0])) {goto endall;};
    iret[1] = bsmort;
    if (CHECK(iret[1])) {goto endall;};



    iret += 2;

    for (TIME=1; TIME<TIMEF; TIME++) {
        double bsitevol[1];
        breeding_site_sim_wrap(bsitevol,bsvol,model_param[bs_alpha],model_param[bs_beta],envir_prec[(int)(TIME-1)]);

        bsvol = bsitevol[0];
        bsmort = (((bsvol > 0.75)) ? (0.5) : (0.0));

        if (*rep >= 0) {
                par[0] = 0.0;
                par[1] = 0.0;
                spop2_step(larva, par, &size_larva, completed_larva, 0);









        }

        ret[0] = size_larva.d;
        if (CHECK(ret[0])) {goto endall;};

        ret += 1;

        iret[0] = bsvol;
        if (CHECK(iret[0])) {goto endall;};
        iret[1] = bsmort;
        if (CHECK(iret[1])) {goto endall;};



        iret += 2;

    }

  endall:

    *success = TIME;

    if (file1 && file1[0]!=' ') {
        file = fopen(file1,"wb");
        if (!file) {
            *success = 0;
        } else {
            rewind(file);

            buffsz = spop2_buffsize(larva);
            buff = spop2_savestate(larva);
            fwrite(&buffsz, sizeof(unsigned int), 1, file);
            fwrite(buff, buffsz, 1, file);
            free(buff);

            fclose(file);
        }
    }

    spop2_free(&larva);

}

int main(int argc, char *argv[]) {
    int no, np, ni, ne, st;

    init(&no, &np, &ni, &ne, &st);

    printf("Number of populations: %d\n", no);
    printf("Number of parameters: %d\n", np);
    printf("Number of intermediates: %d\n", ni);
    printf("Number of environmental variables: %d\n", ne);
    printf("The model is %s\n", st ? "stochastic" : "deterministic");

    destroy();

    return 0;
}


