/* 
 *  This code was automatically generated by PopJSON (v.1.6.0) for Population (v.0.1.11)
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 *  See the GNU General Public License for more details:
 *  <https://www.gnu.org/licenses/>
 */

#include <math.h>
#include "population.h"

#include <limits.h>
#include <dlfcn.h>
#include <libgen.h>
#include <string.h>
#include <stdio.h>
void *breeding_site;
void (*breeding_site_init)(int *, int *, int *, int *, int *);
void (*breeding_site_destroy)(void);
void (*breeding_site_sim)(int *, int *, double *, double *, double *, char **, char **, double *, double *, int *);

void breeding_site_setup() {
    Dl_info info;
    if (dladdr((void *)breeding_site_setup, &info) == 0) {
        fprintf(stderr, "Could not determine library path\n");
        return;
    }

    char path[PATH_MAX];
    strncpy(path, info.dli_fname, PATH_MAX);
    path[PATH_MAX - 1] = '\0';

    char *dir = dirname(path);
    char fullpath[PATH_MAX];
    snprintf(fullpath, PATH_MAX, "%s/%s", dir, "ex9.dylib");

    breeding_site = dlopen(fullpath, RTLD_NOW);
    if (!breeding_site) { fprintf(stderr, "dlopen failed: %s\n", dlerror()); return; };

    *(void **)(&breeding_site_init) = dlsym(breeding_site, "init");
    if (!breeding_site_init) { fprintf(stderr, "dlsym(init) failed: %s\n", dlerror()); dlclose(breeding_site); return; };

    *(void **)(&breeding_site_sim) = dlsym(breeding_site, "sim");
    if (!breeding_site_sim) { fprintf(stderr, "dlsym(sim) failed: %s\n", dlerror()); dlclose(breeding_site); return; };

    *(void **)(&breeding_site_destroy) = dlsym(breeding_site, "destroy");
    if (!breeding_site_destroy) { fprintf(stderr, "dlsym(destroy) failed: %s\n", dlerror()); dlclose(breeding_site); return; };

    int no, np, ni, ne, st;
    breeding_site_init(&no, &np, &ni, &ne, &st);
}

void breeding_site_finish() {
    breeding_site_destroy();
    dlclose(breeding_site);
}

void breeding_site_sim_wrap(double value[1],
        double y00,
        double pr0,
        double pr1,
        double env0) {
    int tf = 2;
    int rep = 1;
    int success;
    double init[1] = {y00};
    double param[2] = {pr0, pr1};
    double envir[3] = {tf, env0, env0};
    double result[2];
    breeding_site_sim(&tf, &rep, envir, param, init, 0, 0, result, 0, &success);
    value[0] = result[1];
}

#define CHECK(x) (isnan(x) || isinf(x))

#define NumPar 5
#define NumPop 2
#define NumInt 4
#define NumEnv 2

#define d2m_a 0
#define d2m_b 1
#define d2m_c 2
#define bs_alpha 3
#define bs_beta 4

#define larva_compare_death 0
#define larva_compare_dev 1
#define larva_death 0
#define larva_dev 1


double dmin(double a, double b) { return a < b ? a : b; }
double dmax(double a, double b) { return a > b ? a : b; }

int TIME;
int TIMEF;

number size_larva_compare;
number size_larva;

double *model_param;
double *envir_temp;
double *envir_prec;

double bsvol;
double bscoef_compare;
double bscoef;
double d2m;


#define briere1(T,a,L,R) (((((T) <= (L))) ? (365.0) : (((((T) >= (R))) ? (365.0) : (dmin(365.0, dmax(1.0, (1.0 / exp(((a) + log((T)) + log(((T) - (L))) + (0.5 * log(((R) - (T))))))))))))))
double define_briere1(double T, double a, double L, double R) {return ((((T) <= (L))) ? (365.0) : (((((T) >= (R))) ? (365.0) : (dmin(365.0, dmax(1.0, (1.0 / exp(((a) + log((T)) + log(((T) - (L))) + (0.5 * log(((R) - (T)))))))))))));}

void fun_hazpar_larva_dev_larva(const number *key, const number num, double *par) {
    double bsitevoldev[1];
    breeding_site_sim_wrap(bsitevoldev,bsvol,model_param[bs_alpha],model_param[bs_beta],envir_prec[(int)(TIME-1)]);

    double coefdev = (1.0 - (size_larva.d / (1.0 + size_larva.d + bsitevoldev[0])));
    double d2m_coef = (coefdev * d2m);

    par[0] = d2m_coef;
    par[1] = sqrt(d2m_coef);
}

void prepare_tprobs(int numcol, double *ttprobs, double *tprobs) {
    int rA, rB, i = 0;
    double sum;
    for (i=0, rB=0; rB<numcol; rB++) {
        sum = 1.0;
        for (rA=0; rA<numcol; rA++, i++) {
            tprobs[i] = sum <= 0.0 ? 1.0 : ttprobs[i] / sum;
            sum -= ttprobs[i];
        }
    }
}

void init(int *no, int *np, int *ni, int *ne, int *st) {
    spop2_set_eps(0.01);

    *no = NumPop;
    *np = NumPar;
    *ni = NumInt;
    *ne = NumEnv;
    *st = 0;

    breeding_site_setup();
}

void parnames(char **names, double *param, double *parmin, double *parmax) {
    char temp[NumPop+NumPar+NumInt+NumEnv][256] = {
        "larva_compare", "larva",
        "d2m_a", "d2m_b", "d2m_c", "bs_alpha", "bs_beta",
        "bsvol", "bscoef_compare", "bscoef", "d2m",
        "temp", "prec",
    };

    int i;
    for (i=0; i<(NumPop+NumPar+NumInt+NumEnv); i++)
        names[i] = strdup(temp[i]);

    param[d2m_a] = -12;
    parmin[d2m_a] = -12;
    parmax[d2m_a] = -12;
    param[d2m_b] = 283.15;
    parmin[d2m_b] = 283.15;
    parmax[d2m_b] = 283.15;
    param[d2m_c] = 308.15;
    parmin[d2m_c] = 308.15;
    parmax[d2m_c] = 308.15;
    param[bs_alpha] = 1;
    parmin[bs_alpha] = 1;
    parmax[bs_alpha] = 1;
    param[bs_beta] = 0.5;
    parmin[bs_beta] = 0.5;
    parmax[bs_beta] = 0.5;
}

void destroy(void) {

    if (breeding_site_destroy) { breeding_site_destroy(); }
    if (breeding_site) { dlclose(breeding_site); breeding_site = NULL; }

}

void sim(int *tf, int *rep, double *envir, double *pr, double *y0, char **file_from, char **file_to, double *ret, double *iret, int *success) {

    char *file0 = *file_from;
    char *file1 = *file_to;

    TIME = 0;
    TIMEF = *tf;

    model_param = pr;

    envir_temp = envir + 1; envir += (int)round(*envir) + 1;
    envir_prec = envir + 1; envir += (int)round(*envir) + 1;


    population larva_compare;
    population larva;

    number num = numZERO;
    char arbiters[3];
    number key[3];
    size_larva_compare = numZERO;
    size_larva = numZERO;
    number completed_larva_compare[3];
    number completed_larva[3];
    double par[3];

    FILE *file;
    number *buff = 0;
    unsigned int buffsz = 0;
    if (file0 && file0[0]!=' ') {
        file = fopen(file0,"rb");
        if (!file) {
            *success = 0;
            goto endall;
        }
        rewind(file);
    }

    if (file0 && file0[0]!=' ') {
        fread(&buffsz, sizeof(unsigned int), 1, file);
        buff = (number *)malloc(buffsz);
        fread(buff, buffsz, 1, file);
        larva_compare = spop2_loadstate(buff);


        free(buff);

        fread(&buffsz, sizeof(unsigned int), 1, file);
        buff = (number *)malloc(buffsz);
        fread(buff, buffsz, 1, file);
        larva = spop2_loadstate(buff);


        free(buff);

    } else {
        arbiters[0] = NOAGE_CONST;
        key[0] = numZERO;
        arbiters[1] = ACC_ERLANG;
        key[1] = numZERO;
        arbiters[2] = STOP;
        key[2] = numZERO;
        larva_compare = spop2_init(arbiters, DETERMINISTIC);
        if (y0[0]) { num.d = y0[0]; spop2_add(larva_compare, key, num); }


        arbiters[0] = NOAGE_CONST;
        key[0] = numZERO;
        arbiters[1] = ACC_ERLANG;
        key[1] = numZERO;
        arbiters[2] = STOP;
        key[2] = numZERO;
        larva = spop2_init(arbiters, DETERMINISTIC);
        larva->arbiters[1]->fun_q_par = fun_hazpar_larva_dev_larva;
        if (y0[1]) { num.d = y0[1]; spop2_add(larva, key, num); }


    }

    if (file0 && file0[0]!=' ') {
        fclose(file);
    }

    bsvol = 0.0;
    bscoef_compare = 0.0;
    bscoef = 0.0;
    d2m = 0.0;

    size_larva_compare = spop2_size(larva_compare);
    size_larva = spop2_size(larva);

    ret[0] = size_larva_compare.d;
    if (CHECK(ret[0])) {goto endall;};
    ret[1] = size_larva.d;
    if (CHECK(ret[1])) {goto endall;};

    ret += 2;

    iret[0] = bsvol;
    if (CHECK(iret[0])) {goto endall;};
    iret[1] = bscoef_compare;
    if (CHECK(iret[1])) {goto endall;};
    iret[2] = bscoef;
    if (CHECK(iret[2])) {goto endall;};
    iret[3] = d2m;
    if (CHECK(iret[3])) {goto endall;};



    iret += 4;

    for (TIME=1; TIME<TIMEF; TIME++) {
        double bsitevol[1];
        breeding_site_sim_wrap(bsitevol,bsvol,model_param[bs_alpha],model_param[bs_beta],envir_prec[(int)(TIME-1)]);

        bsvol = bsitevol[0];
        bscoef_compare = (1.0 - (size_larva_compare.d / (1.0 + size_larva_compare.d + bsvol)));
        bscoef = (1.0 - (size_larva.d / (1.0 + size_larva.d + bsvol)));
        d2m = briere1(envir_temp[(int)(TIME-1)], model_param[d2m_a], model_param[d2m_b], model_param[d2m_c]);

        if (*rep >= 0) {




                par[0] = bscoef_compare;
                par[1] = (bscoef_compare * d2m);
                par[2] = sqrt((bscoef_compare * d2m));
                spop2_step(larva_compare, par, &size_larva_compare, completed_larva_compare, 0);

                double bsitevolmort[1];
                breeding_site_sim_wrap(bsitevolmort,bsvol,model_param[bs_alpha],model_param[bs_beta],envir_prec[(int)(TIME-1)]);

                double coefmort = (1.0 - (size_larva.d / (1.0 + size_larva.d + bsitevolmort[0])));

                par[0] = coefmort;
                par[1] = 0.0;
                par[2] = 0.0;
                spop2_step(larva, par, &size_larva, completed_larva, 0);









        }

        ret[0] = size_larva_compare.d;
        if (CHECK(ret[0])) {goto endall;};
        ret[1] = size_larva.d;
        if (CHECK(ret[1])) {goto endall;};

        ret += 2;

        iret[0] = bsvol;
        if (CHECK(iret[0])) {goto endall;};
        iret[1] = bscoef_compare;
        if (CHECK(iret[1])) {goto endall;};
        iret[2] = bscoef;
        if (CHECK(iret[2])) {goto endall;};
        iret[3] = d2m;
        if (CHECK(iret[3])) {goto endall;};



        iret += 4;

    }

  endall:

    *success = TIME;

    if (file1 && file1[0]!=' ') {
        file = fopen(file1,"wb");
        if (!file) {
            *success = 0;
        } else {
            rewind(file);

            buffsz = spop2_buffsize(larva_compare);
            buff = spop2_savestate(larva_compare);
            fwrite(&buffsz, sizeof(unsigned int), 1, file);
            fwrite(buff, buffsz, 1, file);
            free(buff);

            buffsz = spop2_buffsize(larva);
            buff = spop2_savestate(larva);
            fwrite(&buffsz, sizeof(unsigned int), 1, file);
            fwrite(buff, buffsz, 1, file);
            free(buff);

            fclose(file);
        }
    }

    spop2_free(&larva_compare);
    spop2_free(&larva);

}

int main(int argc, char *argv[]) {
    int no, np, ni, ne, st;

    init(&no, &np, &ni, &ne, &st);

    printf("Number of populations: %d\n", no);
    printf("Number of parameters: %d\n", np);
    printf("Number of intermediates: %d\n", ni);
    printf("Number of environmental variables: %d\n", ne);
    printf("The model is %s\n", st ? "stochastic" : "deterministic");

    destroy();

    return 0;
}


