/* 
 *  This code was automatically generated by PopJSON (v.1.2.5)
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 *  See the GNU General Public License for more details:
 *  <https://www.gnu.org/licenses/>
 */

#include <math.h>
#include "population.h"

#define CHECK(x) (isnan(x) || isinf(x))

#define NumPar 4
#define NumPop 1
#define NumInt 2
#define NumEnv 1

#define d2m_a 0
#define d2m_b 1
#define d2m_c 2
#define d2s_c 3

#define larva_dev 0


double dmin(double a, double b) { return a < b ? a : b; }
double dmax(double a, double b) { return a > b ? a : b; }

int TIME;
int TIMEF;

double *model_param;
double *envir_temp;

double d2m;
double d2s;


#define briere1(T,a,L,R) (((((T) <= (L))) ? (365.0) : (((((T) >= (R))) ? (365.0) : (dmin(365.0, dmax(1.0, (1.0 / exp(((a) + log((T)) + log(((T) - (L))) + (0.5 * log(((R) - (T))))))))))))))

void prepare_tprobs(int numcol, double *ttprobs, double *tprobs) {
    int rA, rB, i = 0;
    double sum;
    for (i=0, rB=0; rB<numcol; rB++) {
        sum = 1.0;
        for (rA=0; rA<numcol; rA++, i++) {
            tprobs[i] = sum <= 0.0 ? 1.0 : ttprobs[i] / sum;
            sum -= ttprobs[i];
        }
    }
}

void init(int *no, int *np, int *ni, int *ne, int *st) {
    spop2_set_eps(0.01);

    *no = NumPop;
    *np = NumPar;
    *ni = NumInt;
    *ne = NumEnv;
    *st = 0;
}

void parnames(char **names, double *param, double *parmin, double *parmax) {
    char temp[NumPop+NumPar+NumInt+NumEnv][256] = {
        "larva",
        "d2m_a", "d2m_b", "d2m_c", "d2s_c",
        "d2m", "d2s",
        "temp",
    };

    int i;
    for (i=0; i<(NumPop+NumPar+NumInt+NumEnv); i++)
        names[i] = strdup(temp[i]);

    param[d2m_a] = -12;
    parmin[d2m_a] = -12;
    parmax[d2m_a] = -12;
    param[d2m_b] = 283.15;
    parmin[d2m_b] = 283.15;
    parmax[d2m_b] = 283.15;
    param[d2m_c] = 308.15;
    parmin[d2m_c] = 308.15;
    parmax[d2m_c] = 308.15;
    param[d2s_c] = 0.2;
    parmin[d2s_c] = 0.2;
    parmax[d2s_c] = 0.2;
}

void destroy(void) {
}

void sim(int tf, int rep, double *envir, double *pr, double *y0, const char *file0, const char *file1, double *ret, double *iret, int *success) {

    TIME = 0;
    TIMEF = tf;

    model_param = pr;

    envir_temp = envir + 1; envir += (int)round(*envir) + 1;


    population larva;

    number num = numZERO;
    char arbiters[2];
    number key[2];
    number size_larva;
    number completed_larva[2];
    double par[2];

    FILE *file;
    number *buff = 0;
    unsigned int buffsz = 0;
    if (file0 && file0[0]!=' ') {
        file = fopen(file0,"rb");
        if (!file) {
            *success = 0;
            goto endall;
        }
        rewind(file);
    }

    if (file0 && file0[0]!=' ') {
        fread(&buffsz, sizeof(unsigned int), 1, file);
        buff = (number *)malloc(buffsz);
        fread(buff, buffsz, 1, file);
        larva = spop2_loadstate(buff);


        free(buff);

    } else {
        arbiters[0] = ACC_ERLANG;
        key[0] = numZERO;
        arbiters[1] = STOP;
        key[1] = numZERO;
        larva = spop2_init(arbiters, DETERMINISTIC);
        if (y0[0]) { num.d = y0[0]; spop2_add(larva, key, num); }


    }

    if (file0 && file0[0]!=' ') {
        fclose(file);
    }

    d2m = 0.0;
    d2s = 0.0;

    size_larva = spop2_size(larva);

    ret[0] = size_larva.d;
    if (CHECK(ret[0])) {goto endall;};

    ret += 1;

    for (TIME=1; TIME<tf; TIME++) {
        d2m = briere1(envir_temp[(TIME-1)], model_param[d2m_a], model_param[d2m_b], model_param[d2m_c]);
        d2s = (model_param[d2s_c] * d2m);

        if (rep >= 0) {
                par[0] = d2m;
                par[1] = d2s;
                spop2_step(larva, par, &size_larva, completed_larva, 0);









        }

        ret[0] = size_larva.d;
        if (CHECK(ret[0])) {goto endall;};

        ret += 1;

        iret[0] = d2m;
        if (CHECK(iret[0])) {goto endall;};
        iret[1] = d2s;
        if (CHECK(iret[1])) {goto endall;};


        iret += 2;

    }

  endall:

    *success = TIME;

    if (file1 && file1[0]!=' ') {
        file = fopen(file1,"wb");
        if (!file) {
            *success = 0;
        } else {
            rewind(file);

            buffsz = spop2_buffsize(larva);
            buff = spop2_savestate(larva);
            fwrite(&buffsz, sizeof(unsigned int), 1, file);
            fwrite(buff, buffsz, 1, file);
            free(buff);

            fclose(file);
        }
    }

    spop2_free(&larva);

}

int main(int argc, char *argv[]) {
    return 0;
}


