/* 
 *  This code was automatically generated by PopJSON (v.1.6.0) for Population (v.0.1.11)
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 *  See the GNU General Public License for more details:
 *  <https://www.gnu.org/licenses/>
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <gsl/gsl_odeiv2.h>
#include <gsl/gsl_errno.h>

#define CHECK(x) (isnan(x) || isinf(x))

#define NumPop 3
#define NumEnv 0
#define NumPar 3
#define NumInt 0

#define sigma 0
#define rho 1
#define beta 2


int TIME;
int TIMEF;

double *model_param;


gsl_odeiv2_system ODE_SYSTEM;
gsl_odeiv2_driver *ODE_DRIVER;
double ODE_HSTART = 0.001;
double ODE_EPS_ABS = 1e-8;
double ODE_EPS_REL = 1e-8;

int ode_func(double t, const double y[], double f[], void *params) {
    int time = (int)floor(t);
    if (time < 0) time = 0;
    if (time >= TIMEF) time = TIMEF - 1;

    double size_xx = y[0];
    double size_yy = y[1];
    double size_zz = y[2];

    f[0] = 0.0;
    f[1] = 0.0;
    f[2] = 0.0;

    double rate_yx_to_xx = (model_param[sigma] * size_yy);
    f[1] -= ((double)1) * rate_yx_to_xx;
    f[0] += ((double)1) * rate_yx_to_xx;

    double rate_x_decay_sigma = (model_param[sigma] * size_xx);
    f[0] -= ((double)1) * rate_x_decay_sigma;

    double rate_x_to_xy = (model_param[rho] * size_xx);
    f[0] -= ((double)1) * rate_x_to_xy;
    f[1] += ((double)1) * rate_x_to_xy;

    double rate_yz_loss_by_xz = (size_xx * size_zz);
    f[1] -= ((double)1) * rate_yz_loss_by_xz;

    double rate_y_decay = size_yy;
    f[1] -= ((double)1) * rate_y_decay;

    double rate_z_production = (size_xx * size_yy);
    f[2] += ((double)1) * rate_z_production;

    double rate_z_decay = (model_param[beta] * size_zz);
    f[2] -= ((double)1) * rate_z_decay;

    return GSL_SUCCESS;
}

void init(int *no, int *np, int *ni, int *ne, int *st) {
    ODE_SYSTEM.function = ode_func;
    ODE_SYSTEM.jacobian = 0;
    ODE_SYSTEM.dimension = NumPop;
    ODE_SYSTEM.params = 0;

    ODE_DRIVER = gsl_odeiv2_driver_alloc_y_new(
        &ODE_SYSTEM,
        gsl_odeiv2_step_rk8pd,
        ODE_HSTART,
        ODE_EPS_ABS,
        ODE_EPS_REL
    );

    *no = NumPop;
    *np = NumPar;
    *ni = NumInt;
    *ne = NumEnv;
    *st = 0;
}

void parnames(char **names, double *param, double *parmin, double *parmax) {
    char temp[NumPop+NumPar+NumInt+NumEnv][256] = {
        "xx", "yy", "zz",
        "sigma", "rho", "beta",
    };

    int i;
    for (i=0; i<(NumPop+NumPar+NumInt+NumEnv); i++)
        names[i] = strdup(temp[i]);

    param[sigma] = 10;
    parmin[sigma] = 10;
    parmax[sigma] = 10;
    param[rho] = 28;
    parmin[rho] = 28;
    parmax[rho] = 28;
    param[beta] = 2.6666666666666665;
    parmin[beta] = 2.6666666666666665;
    parmax[beta] = 2.6666666666666665;
}

void destroy(void) {
    if (ODE_DRIVER != NULL) {
        gsl_odeiv2_driver_free(ODE_DRIVER);
    }
}

void sim(int *tf, int *rep, double *envir, double *pr, double *y0, char **file_from, char **file_to, double *ret, double *iret, int *success) {
    TIME = 0;
    TIMEF = *tf;
    double t = 0.0;

    model_param = pr;


    int status;
    if (ODE_DRIVER) { gsl_odeiv2_driver_reset(ODE_DRIVER); }

    double state[NumPop];
    if (y0[0]) { state[0] = y0[0]; } else { state[0] = 0.0; }
    if (y0[1]) { state[1] = y0[1]; } else { state[1] = 0.0; }
    if (y0[2]) { state[2] = y0[2]; } else { state[2] = 0.0; }

    ret[0] = state[0];
    if (CHECK(ret[0])) {goto endall;};
    ret[1] = state[1];
    if (CHECK(ret[1])) {goto endall;};
    ret[2] = state[2];
    if (CHECK(ret[2])) {goto endall;};

    ret += 3;

    for (TIME=1; TIME<TIMEF; TIME++) {
        t = (double)(TIME-1);
        status = gsl_odeiv2_driver_apply(ODE_DRIVER, &t, t+1.0, state);
        if (status != GSL_SUCCESS) { goto endall; };

        ret[0] = state[0];
        if (CHECK(ret[0])) {goto endall;};
        ret[1] = state[1];
        if (CHECK(ret[1])) {goto endall;};
        ret[2] = state[2];
        if (CHECK(ret[2])) {goto endall;};

        ret += 3;

    }


  endall:

    *success = TIME;
}

int main(int argc, char *argv[]) {
    int no, np, ni, ne, st;

    init(&no, &np, &ni, &ne, &st);

    printf("Number of populations: %d\n", no);
    printf("Number of parameters: %d\n", np);
    printf("Number of intermediates: %d\n", ni);
    printf("Number of environmental variables: %d\n", ne);
    printf("The model is %s\n", st ? "stochastic" : "deterministic");

    destroy();

    return 0;
}


