import numpy
from matplotlib import pyplot as plt
import population as pop

print("Processing ex6a...")
ex6a = pop.model("examples/ex6a.dylib")
t2m = 30.0+numpy.random.random(30)*20-10
t2m = numpy.repeat(t2m,25)
out6a = ex6a.sim(len(t2m),envir={"temp":t2m},pr=ex6a.param,y0={"adult_0_0":100.0})


print("Processing ex1E...")
ex1E = pop.model("examples/ex1E.dylib")
t2m = numpy.arange(0,40,0.01)+273.15
out1Ef = ex1E.sim(len(t2m), envir={"temp":t2m}, pr=ex1E.param)
plt.plot(t2m[1:],out1Ef['iret'][0,:,0],'-',c="black")
plt.xlabel("Temperature (°C)")
plt.ylabel("Development time (days)")
plt.ylim(0,100)
plt.savefig("figures/ex1Ebr.png",bbox_inches="tight",dpi=300)
plt.close()

t2m = 273.15+30.0+numpy.random.randint(-10,10,30)
out1E = ex1E.sim(len(t2m),envir={"temp":t2m},pr=ex1E.param,y0={"larva":100.0})
plt.plot(numpy.arange(1,len(t2m)),out1E['iret'][0,:,0],'-',c="blue", label="Development time (days)")
plt.plot(out1E['ret'][0,:,0],'o-',c="black", label="Number of larvae")
plt.legend()
plt.xlabel("Time (days)")
plt.ylabel(" ")
plt.ylim(0,110)
plt.savefig("figures/ex1E.png",bbox_inches="tight",dpi=300)
plt.close()

print("Processing ex1a...")
ex1a = pop.model("examples/ex1a.dylib")
out1a = ex1a.sim(30,y0={"larva":100.0})
plt.plot(out1a['ret'][0,:,0],'o-',c="black")
plt.savefig("figures/ex1a.png",bbox_inches="tight",dpi=300)
plt.close()

print("Processing ex1a and ex1b...")
ex1a = pop.model("examples/ex1a.dylib")
ex1b = pop.model("examples/ex1b.dylib")
for n in range(3):
    out1b = ex1b.sim(30,y0={"larva":100.0})
    plt.plot(out1b['ret'][0,:,0],'o')
out1a = ex1a.sim(30,y0={"larva":100.0})
plt.plot(out1a['ret'][0,:,0],'-',c="black")
plt.savefig("figures/ex1b.png",bbox_inches="tight",dpi=300)
plt.close()

print("Processing ex2a...")
ex2a = pop.model("examples/ex2a.dylib")
out2a = ex2a.sim(30,y0={"larva":100.0})
plt.plot(out2a['ret'][0,:,0],'o-',c="black",label="Larva alive")
plt.plot(numpy.arange(1,30),out2a['iret'][0,:,0],'o-',c="red",label="Larva dead")
plt.plot(numpy.arange(1,30),out2a['iret'][0,:,1],'o-',c="blue",label="Pupa")
plt.legend()
plt.savefig("figures/ex2a.png",bbox_inches="tight",dpi=300)
plt.close()

print("Processing ex3a...")
ex3a = pop.model("examples/ex3a.dylib")
out3a = ex3a.sim(30,y0={"adult":100.0})
plt.plot(out3a['ret'][0,:,0],'o-',c="black",label="Adult alive")
plt.plot(numpy.arange(1,30),out3a['iret'][0,:,0],'o-',c="red",label="Adult dead")
plt.plot(numpy.arange(1,30),out3a['iret'][0,:,1],'o-',c="blue",label="Gravid females")
plt.plot(numpy.arange(1,30),out3a['iret'][0,:,2],'o-',c="green",label="Newly laid eggs")
plt.legend()
plt.savefig("figures/ex3a.png",bbox_inches="tight",dpi=300)
plt.close()

print("Processing ex3a and ex3b...")
ex3a = pop.model("examples/ex3a.dylib")
ex3b = pop.model("examples/ex3b.dylib")
out3a = ex3a.sim(30,y0={"adult":100.0})
plt.plot(numpy.arange(1,30),out3a['iret'][0,:,2],'o-',c="black",label="Newly laid eggs")
for n in range(3):
    out3b = ex3b.sim(30,y0={"adult":100.0})
    plt.plot(numpy.arange(1,30),out3b['iret'][0,:,2],'o',c="blue")
plt.legend()
plt.savefig("figures/ex3b.png",bbox_inches="tight",dpi=300)
plt.close()

print("Processing ex4a...")
ex4a = pop.model("examples/ex4a.dylib")
out4a = ex4a.sim(30,y0={"adult":100.0})
plt.plot(out4a['ret'][0,:,0],'o-',c="black",label="Adult alive")
plt.plot(numpy.arange(1,30),out4a['iret'][0,:,0],'o-',c="red",label="Adult dead")
plt.plot(numpy.arange(1,30),out4a['iret'][0,:,1],'o-',c="blue",label="Gravid females")
plt.plot(numpy.arange(1,30),out4a['iret'][0,:,2],'o-',c="green",label="Newly laid eggs")
plt.plot(numpy.arange(1,30),out4a['iret'][0,:,3],'o-',c="orange",label="Total number of eggs")
plt.legend()
plt.savefig("figures/ex4a.png",bbox_inches="tight",dpi=300)
plt.close()

print("Processing ex5a...")
ex5a = pop.model("examples/ex5a.dylib")
t2m = [273.15+30.0 for n in range(120)]
out5a30 = ex5a.sim(len(t2m),{"temp":t2m},pr=ex5a.param,y0={"immat":100.0})
t2m = [273.15+15.0 for n in range(120)]
out5a15 = ex5a.sim(len(t2m),{"temp":t2m},pr=ex5a.param,y0={"immat":100.0})
plt.plot(out5a30['ret'][0,:,0],'-', c="black",lw=1,label="Immatures (30°C)")
plt.plot(out5a30['ret'][0,:,1],'-', c="black",lw=2,label="Adults (30°C)")
plt.plot(out5a15['ret'][0,:,0],'-', c="blue",lw=1,label="Immatures (15°C)")
plt.plot(out5a15['ret'][0,:,1],'-', c="blue",lw=2,label="Adults (15°C)")
plt.xlabel("Time (days)")
plt.ylabel("")
plt.legend()
plt.savefig("figures/ex5a.png",bbox_inches="tight",dpi=300)
plt.close()
